blank_issues_enabled: false
contact_links:
  - name: "RealTimeMod 2 - Wiki"
    url: https://github.com/northwesttrees-gaming/RealTimeMod-Reborn/wiki
    about: Official place for information about the mod!
  - name: "RealTimeMod Forge - GitHub"
    url: https://github.com/northwesttrees-gaming/Real-Time-Mod
    about: GitHub for the Forge version of Real Time Mod!
